# Generated by Django 4.2.27 on 2026-01-02 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_usr2_art2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art2',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='article.usr2'),
        ),
    ]
