# Generated by Django 4.2.27 on 2026-01-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_art4_tag4'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
