# Generated by Django 4.2.27 on 2025-12-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=20)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
    ]
