# Generated by Django 4.2.27 on 2026-01-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('datejoined', models.DateField(auto_now_add=True)),
                ('visitcount', models.BigIntegerField(default=0)),
                ('profile', models.TextField()),
                ('website', models.URLField()),
                ('age', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
