# Generated by Django 4.2.27 on 2026-01-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbook', '0003_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='creater',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
