# Generated by Django 4.2.27 on 2026-01-01 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newbook', '0004_tag_creater_tag_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['-datejoined']},
        ),
        migrations.AlterModelTable(
            name='author',
            table='author_info',
        ),
    ]
