# Generated by Django 4.2.27 on 2026-01-01 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newbook', '0005_alter_author_options_alter_author_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='newbook_author',
        ),
    ]
