# Generated by Django 4.2.27 on 2026-01-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbook', '0006_alter_author_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='telphone',
            field=models.CharField(default='', max_length=15, unique=True),
        ),
    ]
